Jonnitto:
  AssetList:
    externalTarget: _blank
    assetExternal: 'image,video,pdf'
    text:
      headlineTag: strong
    thumbnail:
      headlineTag: strong
      maximumWidth: 200

TYPO3:
  Neos:
    userInterface:
      translation:
        autoInclude:
          Jonnitto.AssetList:
            - 'NodeTypes/*'
    typoScript:
      autoInclude:
        Jonnitto.AssetList: true
  Flow:
    mvc:
      routes:
        'Jonnitto.AssetList': true
