Jonnitto:
  AssetList:
    includeCss: true
    container: false
    externalTarget: _blank
    assetExternal: 'image,video,pdf'
    text:
      headlineTag: strong
    thumbnail:
      headlineTag: strong
      maximumWidth: 400

Neos:
  Media:
    thumbnailGenerators:
      Neos\Media\Domain\Model\ThumbnailGenerator\DocumentThumbnailGenerator:
        resolution: 300
  Neos:
    userInterface:
      translation:
        autoInclude:
          Jonnitto.AssetList:
            - 'NodeTypes/*'
    fusion:
      autoInclude:
        Jonnitto.AssetList: true
  Flow:
    mvc:
      routes:
        'Jonnitto.AssetList': true
