Jonnitto:
  AssetList:
    includeCss: true
    container: false
    externalTarget: _blank
    text:
      headlineTag: strong
    thumbnail:
      headlineTag: strong
      maximumWidth: 400

Carbon:
  IncludeAssets:
    Packages:
      'Jonnitto.AssetList':
        Package: 'Jonnitto.AssetList'
        ConditionPrototype: 'Jonnitto.AssetList:IncludeAssets'
        Path:
          File:
            CSS: 'Public'
        General:
          Head: Main.css

Neos:
  Media:
    thumbnailGenerators:
      Neos\Media\Domain\Model\ThumbnailGenerator\DocumentThumbnailGenerator:
        resolution: 300
  Neos:
    userInterface:
      translation:
        autoInclude:
          Jonnitto.AssetList:
            - 'NodeTypes/*'
    fusion:
      autoInclude:
        Jonnitto.AssetList: true
